---
  - name: New user
    user: name=andrew password={{andrewpassword}} comment="Andrew Innes" shell=/bin/bash groups=sudo append=yes

  - name: Placing key
    authorized_key: user=andrew key=https://github.com/andrewc12.keys
